eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8010/eureka/
---
spring:
   profiles: dc
heroes: Superman, Mujer Maravilla, Batman, Flash
---
spring:
   profiles: marvel
heroes: IronMan, Thor, Spiderman, CapitanAmerica, Hulk
