eureka:
   client:
      serviceUrl:
         defaultZone: http://eureka-primary:8011/eureka/, http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
   profiles: dc
heroes: Superman, Mujer Maravilla, Batman, Flash, Mifarma
---
spring:
   profiles: marvel
heroes: IronMan, Thor, Spiderman, Capitan America, Hulk, Inkafarma
