eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
   profiles:
      dcwords: Superman,MujerMaravilla,Batman,Flash
---
spring:
   profiles:
      marvelwords: IronMan,Thor,Spiderman,CapitanAmerica,Hulk
